# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
